Feature/progress indicator
rockcontent/rock-ui pull request #89
Opened 2021-04-23 11:18 UTC by KelvinCS

- Create new progress indicator component;
- Add `useColorScheme` util, that returns the `base` and `accent` colors given a color

2021-04-23 16:26 UTC, benits commented on src/components/progress-indicator/index.tsx
> +} from './progress-indicator';
@KelvinCS , não consegui encontrar o export do progress-indicator no index.ts na raiz de src. Confere ou eu comi barriga?

2021-04-23 16:32 UTC, benits commented on src/components/progress-indicator/step.tsx
> +const Container = styled(Flex)`
@KelvinCS , queria saber sua opinião, você não acha que esse arquivo está muito grande? tem algum motivo especifico para não colocar esse estilo em um arquivo a parte? tipo step-styled.ts...

faz sentido?

2021-04-23 16:37 UTC, benits requested changes
Comentarios

2021-04-26 11:04 UTC, KelvinCS commented on src/components/progress-indicator/step.tsx
> +const Container = styled(Flex)`
Done!

2021-04-26 11:07 UTC, KelvinCS commented on src/components/progress-indicator/step.tsx
> +const Container = styled(Flex)`
Faz sentido!

2021-04-26 11:08 UTC, merged